version: '3.3'

services:
  search:
    build:
      dockerfile: docker/search.dockerfile
      context: .
    image: hw3_search:latest

  user:
    build:
      dockerfile: docker/user_data.dockerfile
      context: .
    image: hw3_user:latest

  geo:
    build:
      dockerfile: docker/geo_data.dockerfile
      context: .
    image: hw3_geo:latest

  unit_test_search:
    image: hw3_search:latest
    entrypoint: pytest --cov=src/search --cov-config=.coveragerc src/search/
#    volumes:
#      - ./src/search:/search_app/src/search

  integration_tests:
    image: hw3_search:latest
    entrypoint: pytest -vs src/tests/
#    volumes:
#      - ./src/tests:/search_app/src/tests
    depends_on:
      - search
      - user
      - geo
